// Builds the branded "sign your listing agreement" block that gets inserted
// directly into an email in the inline composer — the same pattern as the
// quote (listing options) block. The contract PDF itself is generated by the
// `generate-contract` edge function; this block links the seller to the
// secure signing page.

import { supabase } from "@/integrations/supabase/client";

export interface ListingAgreementBlockResult {
  html: string;
  signUrl: string;
  signToken: string;
  contractId?: string | null;
}

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const fmtUsd = (n: number) =>
  n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export interface ListingAgreementBlockInput {
  submissionId: string;
  cemetery?: string | null;
  /** Total authorized minimum (guaranteed net) shown in the summary card. */
  authorizedMinTotal?: number | null;
  plotCount?: number | null;
  /** Passed through to generate-contract as field overrides. */
  overrides?: Record<string, unknown>;
}

export const buildListingAgreementHtml = (opts: {
  signUrl: string;
  cemetery?: string | null;
  authorizedMinTotal?: number | null;
  plotCount?: number | null;
}): string => {
  const cem = (opts.cemetery || "").trim();
  const rows: string[] = [];
  if (cem) rows.push(["Cemetery", esc(cem)].join("\u0000"));
  if (opts.plotCount && opts.plotCount > 0) {
    rows.push(["Property", `${opts.plotCount} space${opts.plotCount === 1 ? "" : "s"}`].join("\u0000"));
  }
  if (opts.authorizedMinTotal && opts.authorizedMinTotal > 0) {
    rows.push(["Guaranteed net to you", fmtUsd(opts.authorizedMinTotal)].join("\u0000"));
  }

  const rowsHtml = rows
    .map((r) => {
      const [label, value] = r.split("\u0000");
      return `<tr>
        <td style="padding:7px 0;font-family:Georgia,serif;font-size:13px;color:#7c6f5a;">${label}</td>
        <td style="padding:7px 0;font-family:Georgia,serif;font-size:14px;color:#1f2937;text-align:right;font-weight:bold;">${value}</td>
      </tr>`;
    })
    .join("");

  return `
<div data-listing-agreement="1" style="margin:18px 0;">
  <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="border-collapse:collapse;border:1px solid #e7e2d8;border-radius:12px;background:#fdfbf7;">
    <tr>
      <td style="padding:22px 24px;">
        <p style="font-family:Georgia,serif;font-size:10px;letter-spacing:.28em;text-transform:uppercase;color:#7c3a2e;margin:0 0 8px;font-weight:bold;">Exclusive Right-to-Sell Agreement</p>
        <p style="font-family:Georgia,serif;font-size:18px;color:#1f2937;margin:0 0 12px;">Your listing agreement is ready to sign</p>
        <p style="font-family:Georgia,serif;font-size:14px;line-height:1.6;color:#4a5568;margin:0 0 16px;">
          Everything has been prepared for you. Review the agreement, add the last couple of details,
          and sign electronically — it takes about two minutes. Your signature is legally binding
          under the U.S. E-Sign Act and Texas UETA.
        </p>
        ${rowsHtml ? `<table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="border-collapse:collapse;border-top:1px solid #e7e2d8;border-bottom:1px solid #e7e2d8;margin:0 0 18px;">${rowsHtml}</table>` : ""}
        <table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin:0 auto 14px;">
          <tr>
            <td align="center" style="background:#1f2a37;border-radius:8px;">
              <a href="${esc(opts.signUrl)}" style="display:inline-block;padding:14px 30px;color:#ffffff;text-decoration:none;font-family:Georgia,serif;font-size:15px;">
                Review &amp; sign your agreement &rarr;
              </a>
            </td>
          </tr>
        </table>
        <p style="font-family:Georgia,serif;font-size:11px;line-height:1.6;color:#9a8f7a;margin:0;text-align:center;word-break:break-all;">
          Or paste this link into your browser: ${esc(opts.signUrl)}
        </p>
      </td>
    </tr>
  </table>
</div>`.trim();
};

/** Generates (or regenerates) the listing agreement and returns the email block. */
export const buildListingAgreementBlock = async (
  input: ListingAgreementBlockInput,
): Promise<ListingAgreementBlockResult> => {
  const { data, error } = await supabase.functions.invoke("generate-contract", {
    body: {
      submission_id: input.submissionId,
      kind: "listing_agreement",
      overrides: input.overrides ?? {},
    },
  });
  if (error) throw new Error(error.message);
  if ((data as any)?.error) throw new Error(String((data as any).error));
  const signToken = (data as any)?.sign_token as string | undefined;
  if (!signToken) throw new Error("The contract was generated but no signing link came back.");

  const signUrl = `${window.location.origin}/sign/${signToken}`;
  return {
    signToken,
    signUrl,
    contractId: (data as any)?.contract_id ?? null,
    html: buildListingAgreementHtml({
      signUrl,
      cemetery: input.cemetery,
      authorizedMinTotal: input.authorizedMinTotal ?? null,
      plotCount: input.plotCount ?? null,
    }),
  };
};
