export type RestlandGarden = {
  name: string;
  /** Sub-sections (usually a cryptorium) that sit inside the parent garden. */
  children?: string[];
  note?: string;
};

/**
 * Complete Restland Memorial Park section list, as published by the cemetery.
 * Entries with children are parent sections containing a cryptorium or court.
 */
export const RESTLAND_GARDENS: RestlandGarden[] = [
  { name: "Abbey Estates" },
  { name: "Abbey Estates 1" },
  { name: "Abbey Estates 2" },
  { name: "Abbey Mausoleum", note: "North · Center · South" },
  { name: "Acacia" },
  { name: "Acacia Lawn" },
  { name: "Ascension" },
  { name: "Babyland" },
  { name: "Babyland 2" },
  { name: "Babyland 3" },
  { name: "Babyland 4" },
  { name: "Babyland 5" },
  { name: "Bahai" },
  { name: "Beth Torah" },
  { name: "Binnerri" },
  { name: "Brookview Estates" },
  { name: "C" },
  { name: "Capitol Estates" },
  { name: "Chapel" },
  { name: "Chapel Gardens Cremorials" },
  { name: "Chapel Gardens Mausoleum" },
  { name: "Chapel Gardens Mausoleum 2" },
  { name: "Christian Orthodox" },
  { name: "Colonial" },
  { name: "Companion A" },
  { name: "Companion B" },
  { name: "Companion C" },
  { name: "Companion D" },
  { name: "Compassion" },
  { name: "Court of Hope" },
  { name: "Court of Faith" },
  { name: "Court of Meditation" },
  { name: "Court of Remembrance" },
  { name: "Creekside Estates" },
  { name: "Creekview Walled Estates" },
  { name: "Crestview" },
  { name: "Cross" },
  { name: "Devotion" },
  { name: "Entrance Gardens" },
  { name: "Entrance Garden Estates" },
  { name: "Estates of Restland, The" },
  { name: "Eternity", children: ["Tu-Dam", "Loving Cloud", "Rest"] },
  { name: "Evergreen" },
  { name: "Evergreen Babyland" },
  { name: "Faith" },
  { name: "Faith Urn Garden" },
  { name: "Field of Honor" },
  { name: "Floral Hill" },
  { name: "Floyd Cemetery" },
  { name: "Fountain View" },
  { name: "Four Seasons" },
  { name: "Freedom" },
  { name: "Gabriel" },
  { name: "Gateway" },
  { name: "Gateway North" },
  { name: "Gethsemane" },
  { name: "Good Shepherd" },
  { name: "Gospel" },
  { name: "Highland Gardens" },
  { name: "Holy Family" },
  { name: "Honor" },
  { name: "Islamic Garden" },
  { name: "Kever Israel" },
  { name: "Lakeview" },
  { name: "Last Supper" },
  { name: "Love" },
  { name: "Loving Cloud" },
  { name: "Mapelwood" },
  { name: "Masonic" },
  { name: "Memories", children: ["Memories Cryptorium (Court)"] },
  { name: "Mirrow Lake Estates" },
  { name: "Mount Sinai" },
  { name: "Mount Zion" },
  { name: "Mount Vernon" },
  { name: "Nards" },
  { name: "Parkview" },
  { name: "Peace" },
  { name: "Pioneer" },
  { name: "Plaza" },
  { name: "Prayer" },
  { name: "Psalms" },
  { name: "Reflections Garden", children: ["Reflections Court"] },
  { name: "Rest" },
  { name: "Rock Garden" },
  { name: "Rose" },
  { name: "Salvation Army" },
  { name: "Serenity Garden", children: ["Serenity Court"] },
  { name: "Sunset" },
  { name: "Ten Commandments" },
  {
    name: "Terrace Gardens",
    children: ["Court of Hope", "Court of Remembrance", "Court of Meditation"],
  },
  { name: "Tower" },
  { name: "Tranquility Estates" },
  { name: "Trinity" },
  { name: "Tu-Dam" },
  {
    name: "United Jewish Cemetery",
    children: ["Mount Sinai", "Beth Torah", "Mount Zion"],
  },
  { name: "Urn Garden" },
  { name: "Valley View" },
  { name: "Veteran's 1" },
  { name: "Veteran's 2" },
  { name: "Veteran's 3" },
  { name: "Veteran's 4" },
  { name: "Whispering Waters" },
  { name: "Whispering Waters 2" },
  { name: "Whispering Waters Estates" },
  { name: "Whispering Waters Mausoleum" },
  { name: "Wildwood Garden" },
  { name: "Wildwood Rill" },
  { name: "Wisdom" },
  { name: "Woodland" },
  { name: "Woodland Estates" },
];
