// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-listings.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { z } from "npm:zod@^4.4.3";
var search_listings_default = defineTool({
  name: "search_listings",
  title: "Search active listings",
  description: "Search active cemetery property listings by cemetery name, city, or plot type. Returns id, cemetery, city, plot type, spaces, and section.",
  inputSchema: {
    query: z.string().optional().describe("Free-text match against cemetery, city, or plot type."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("listings").select("id, cemetery, city, plot_type, section, spaces, status").eq("status", "active").limit(limit ?? 20);
    if (query && query.trim()) {
      const term = `%${query.trim()}%`;
      q = q.or(`cemetery.ilike.${term},city.ilike.${term},plot_type.ilike.${term}`);
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { listings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-listing.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_listing_default = defineTool2({
  name: "get_listing",
  title: "Get listing details",
  description: "Fetch full public details for a single active listing by id.",
  inputSchema: {
    id: z2.string().uuid().describe("Listing UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("listings").select("id, cemetery, city, plot_type, section, spaces, asking_price, description, status, photos").eq("id", id).eq("status", "active").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Listing not found or not active." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { listing: data }
    };
  }
});

// src/lib/mcp/tools/submit-inquiry.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { z as z3 } from "npm:zod@^4.4.3";
var submit_inquiry_default = defineTool3({
  name: "submit_inquiry",
  title: "Submit buyer/seller inquiry",
  description: "Create a new inquiry (buyer question, seller quote request, or general contact) that will land in the Texas Cemetery Brokers admin inbox.",
  inputSchema: {
    name: z3.string().min(1).describe("Full name of the person inquiring."),
    email: z3.string().email().describe("Contact email."),
    phone: z3.string().optional().describe("Contact phone (optional)."),
    kind: z3.enum(["buyer", "seller", "general"]).describe("Type of inquiry."),
    cemetery: z3.string().optional().describe("Cemetery of interest (optional)."),
    message: z3.string().min(1).describe("The message body.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, email, phone, kind, cemetery, message }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("submissions").insert({
      name,
      email,
      phone: phone ?? null,
      kind,
      cemetery: cemetery ?? null,
      message,
      source: "mcp"
    }).select().maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Inquiry received. Reference: ${data?.id ?? "n/a"}` }],
      structuredContent: { submission: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "texas-cemetery-brokers-mcp",
  title: "Texas Cemetery Brokers",
  version: "0.1.0",
  instructions: "Tools for the Texas Cemetery Brokers marketplace. Use `search_listings` to find active cemetery properties, `get_listing` to fetch details, and `submit_inquiry` to send a buyer/seller inquiry into the brokerage inbox.",
  tools: [search_listings_default, get_listing_default, submit_inquiry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
